development:
  adapter: postgresql
  encoding: utf8
  database: movies_development
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: movies_production
  pool: 5
  username: 
  password:
